CREATE OR REPLACE TRIGGER TRG_AUDIT_STOCK_BATCHES
AFTER INSERT OR UPDATE OR DELETE ON STOCK_BATCHES
FOR EACH ROW
BEGIN

    INSERT INTO AUDIT_LOG
    (
        AUDIT_ID,
        USERNAME,
        ACTION_TYPE,
        TABLE_NAME,
        ACTION_DATE,
        DESCRIPTION
    )
    VALUES
    (
        AUDIT_SEQ.NEXTVAL,
        USER,
        'STOCK_BATCH_CHANGE',
        'STOCK_BATCHES',
        SYSTIMESTAMP,
        'Stock batch record modified'
    );

END;
/
